### PR TITLE
update CI

### PR DESCRIPTION
**Pull request by VoidxHoshi**
replace commands with GitHub Actions options

### CODE REVIEW

**Comment by txyyh** [comment]
图片
Where is the version v1

**Comment by txyyh** [comment]
It may conflict with renovate bot (anyway it's not in github marketplace)

**Comment by asuka-mio** [comment]
> It may conflict with renovate bot (anyway it's not in github marketplace) @asuka-mio review what i said is true

no matter

**Comment by txyyh** [comment]
I will pick it into branch 1.7.x.x

**Pull request merged**
